# Generated by Django 5.2.4 on 2025-07-15 11:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_id', models.CharField(max_length=30)),
                ('downSpeedMBit', models.PositiveIntegerField(null=True)),
                ('upSpeedMBit', models.PositiveIntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
