# Generated by Django 5.2.4 on 2025-07-16 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='line_id',
            new_name='home_id',
        ),
    ]
