# Generated by Django 5.2.4 on 2025-07-16 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_line_id_account_home_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='downSpeedMBit',
            new_name='down_speed_mbit',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='upSpeedMBit',
            new_name='up_speed_mbit',
        ),
    ]
