# Generated by Django 5.2.4 on 2025-07-16 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_downspeedmbit_account_down_speed_mbit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='home_id',
            new_name='line_id',
        ),
    ]
