# Generated by Django 5.2.4 on 2025-07-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_home_id_account_line_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='line_id',
            field=models.CharField(max_length=21),
        ),
    ]
