# Generated by Django 5.2.4 on 2026-05-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_line_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
