# Generated by Django 5.2.4 on 2026-05-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_password_account_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='down_speed_mbit',
            field=models.PositiveIntegerField(null=True, verbose_name='Download Speed (in MBit/s)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='line_id',
            field=models.CharField(max_length=21, unique=True, verbose_name='Line ID'),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(blank=True, help_text='Leave empty, if you do not want to change the password.', max_length=128, null=True, verbose_name='PPPoE Password'),
        ),
        migrations.AlterField(
            model_name='account',
            name='up_speed_mbit',
            field=models.PositiveIntegerField(null=True, verbose_name='Upload Speed (in MBit/s)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='PPPoE User'),
        ),
    ]
