# Generated by Django 5.2.4 on 2026-05-06 12:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_account_down_speed_mbit_alter_account_line_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=128)),
                ('circuit_id', models.CharField(max_length=128)),
                ('remote_id', models.CharField(max_length=128)),
                ('ip_address', models.CharField(max_length=18)),
                ('ipv6_prefix', models.CharField(max_length=43)),
                ('ipv6_pd_prefix', models.CharField(max_length=43)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now_add=True)),
                ('terminated_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
